language: python

python:
  - "3.6"

sudo: enabled

install:
  - "pip install -r requirements.txt"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS=testing

before_script:
  - psql -c 'create database test_db;' -U sendit

script:
  - python3 -m pytest --cov=app tests/

after_success:
- coveralls